Repository eProsima/ShapesDemo, pull requests merged in 2024-10, with the labels that each got.

#181 [21784] Bump version to 3.1.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  shapes-demo-ros2.repos
  shapes-demo.repos
  version.pri
Labels: ci-pending

#183 [21890] Update commercial support section in project README
  README.md
Labels: skip-ci

#184 [21882] Branch out 3.2.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  shapes-demo-ros2.repos
  shapes-demo.repos
  version.pri
Labels: ci-pending

#185 [21882] Branch out 3.1.x
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: skip-ci

#186 Set Fast CDR version as 2.2.x development version in `master`
  shapes-demo-ros2.repos
  shapes-demo.repos
Labels: ready-to-merge

#187 Fix Fast CDR version in .repos files
  shapes-demo-ros2.repos
  shapes-demo.repos
Labels: ready-to-merge
