Repository eProsima/ShapesDemo, pull requests merged in 2024-07, with the labels that each got.

#150 [21229] Improve CI workflows in master
  .github/workflows/build.yml
  .github/workflows/config/build.meta
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  RELEASE_SUPPORT.md
Labels: ready-to-merge

#156 [21229] Remove windows nightly job for 2.6.x
  .github/workflows/nightly-windows-ci.yml
Labels: skip-ci

#158 [21229] Fix nightly jobs and move 2.6.x to weekly CI
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: ready-to-merge, skip-ci

#160 [21267] Fix weekly cron expression
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#159 [21137] Account for changes on RTPS writer refactor
  src/shapesdemo/ShapePublisher.cpp
Labels: ci-pending

#161 [21311] Bump version to 2.14.3
  version.pri
Labels: ci-pending

#162 [21310] Bump version to v2.13.6
  shapes-demo-ros2.repos
  shapes-demo.repos
  version.pri
Labels: skip-ci

#163 [21310] Set 2.13.x as EOL
  .github/pull_request_template.md
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
Labels: skip-ci

#164 [21301] Remove `WriterProxyData` from public APIs
  include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
Labels: ready-to-merge

#166 [21374] Refactor `TopicDataType`
  include/eprosimashapesdemo/shapesdemo/ShapeInfo.h
  src/shapesdemo/ShapePublisher.cpp
  types/KeylessShapeTypePubSubTypes.cxx
  types/KeylessShapeTypePubSubTypes.hpp
  types/ShapePubSubTypes.cxx
  types/ShapePubSubTypes.hpp
Labels: ready-to-merge

#165 [21321] Update references to `Time_t` and `Duration_t`
  include/eprosimashapesdemo/shapesdemo/ShapeHistory.h
  include/eprosimashapesdemo/shapesdemo/ShapeInfo.h
  src/qt/publishdialog.cpp
  src/qt/subscribedialog.cpp
  src/shapesdemo/ShapeHistory.cpp
Labels: ready-to-merge

#167 [21313] Add support to select type propagation policy
  forms/participantdialog.ui
  include/eprosimashapesdemo/qt/optionsdialog.h
  include/eprosimashapesdemo/qt/participantdialog.h
  include/eprosimashapesdemo/shapesdemo/ShapeHistory.h
  include/eprosimashapesdemo/shapesdemo/ShapeInfo.h
  include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
  src/qt/optionsdialog.cpp
  src/qt/participantdialog.cpp
  src/qt/subscribedialog.cpp
  src/shapesdemo/ShapeHistory.cpp
  src/shapesdemo/ShapePublisher.cpp
  src/shapesdemo/ShapesDemo.cpp
Labels: ci-pending

#169 [21322] Remove new line character at the end of `SHAPESVERSION` cmake variable
  CMakeLists.txt
Labels: ci-pending
