Repository eProsima/ShapesDemo, pull requests merged in 2025-06, with the labels that each got.

#205 [23269] Update PR template and nighties due to EOL versions
  .github/pull_request_template.md
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
Labels: skip-ci

#206 [23269] Branch out 3.3.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  shapes-demo-ros2.repos
  shapes-demo.repos
  version.pri
Labels: ci-pending

#211 Remove deprecated windows-2019 runner
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/windows-ci.yml
Labels: ready-to-merge
